### ISSUE TITLE
Verkaufsstellen integrieren 

### ISSUE THREAD

**Issue by J0hnHawk** [J0hnHawk/FS17_WebStats#15]
Verkaufststellen für Waren einbauen

**Comment by bl4ckdog** [comment]
Verkaufsstellen sind eine sehr schöne Idee - gibt es dann auch eine Seite, auf der die Verkaufspreise angezeigt werden, so wie man das "in-game" schon kennt?

**Comment by J0hnHawk** [comment]
Wenn ich herausgefunden habe, wie sich die Preise berechnen - ich hab da einen Ansatz, muss mich aber erst noch schlau lesen, bzw. Mathe lernen. ;-)

**Comment by J0hnHawk** [comment]
Verkaufsstellen und -preise ergänzt (e3bfa68e760c3b6ba3458a11e70b4886c5770e83)
Preise passen leider noch nicht immer
