### ISSUE TITLE
Invalid Argument in loadConfig on Line 84

### ISSUE THREAD

**Issue by bl4ckdog** [J0hnHawk/FS17_WebStats#30]
Guten Tag zusammen. 
Grundsätzlich gibt es diesen Fehler, den ich nicht entfernen kann:

> Warning: Invalid argument supplied for foreach() in /var/www/vhosts/freizeitbauern.tk/httpdocs/panel/include/loadConfig.php on line 84

Ebenso werden die Tier-Statistiken nicht ausgelesen.

![2018-01-12 10_02_40-goldcrest valley webstats opera](https://user-images.githubusercontent.com/11622279/34867320-fa33b692-f77f-11e7-86ee-5e661a5b3032.png)

Mir ist bekannt, dass die Umstellung zum Einlesen der Kartenkonfigurationen aktuell in Arbeit ist und fehler enthalten kann. Vielleicht hilft das ja bei der Beseitigung.

Grüße =)

**Comment by J0hnHawk** [comment]
Ich hab mich entschlossen, die alten Kartenkonfigurationen nicht mehr anzupassen. Den Hauptvorteil von XML Konfigurationen sehe ich bei den FabrikScripten. Im Grundspiel gibt es die bekanntlich nicht. ;-)
Im Programm gibt es jetzt eine Abfrage ob XML Konfiguration oder nicht. Goldcrest Valley sollte jetzt wieder laufen wie zuvor. Kannst du das mal testen?

**Comment by bl4ckdog** [comment]
Hallöchen :) 
Die aktuelle Version sieht schon besser aus 👍 
Aktuelle Map auf dem Server: Goldcrest Valley
Ausgewählte Map in den WebStats: Goldcrest Valley

Allerdings bleibt noch eine Fehlermeldung übrig. 
`Notice: Undefined offset: 8 in /var/www/vhosts/freizeitbauern.tk/httpdocs/panel/include/loadConfig.php on line 58`

Diese ist auf jeder Seite in den Webstats sichtbar.

![2018-01-14 13_24_37-goldcrest valley webstats opera](https://user-images.githubusercontent.com/11622279/34915888-912cdd62-f92e-11e7-9ede-665b139f6e95.png)

**Comment by alex83we** [comment]
Da solltest du in deiner map.txt folgendes unter der Kartengröße ändern bzw. anpassen 
![screenshot_31](https://user-images.githubusercontent.com/10686163/34915947-93fe33c8-f92f-11e7-9bb6-2fd7f2c82fe4.png)

in deinem Fall sollte da JohnHawk in zeile 7 stehen und in Zeile 8 Version der Karten Konfiguration 1.0 so das es am ende so ausschaut wen du auf Info klickst 
![screenshot_32](https://user-images.githubusercontent.com/10686163/34915958-e40b5e04-f92f-11e7-8d8d-3d19a3b1c8ed.png)

sollte das noch immer nicht helfen dann einfach in der Zeile 9 ein Leerzeichen einfügen  denn da kommt normaler weise die Ausgabe hin XML in deinem Fall hast du keine XML Ausgabe

**Comment by bl4ckdog** [comment]
Juten Tach - Das leerzeichen in Zeile 9 hat zur Beseitigung der Fehleranzeige beigetragen. 
Bitte dementsprechend noch in den Sourcecodes der jeweiligen "map.txt" anpassen :-) 

thx a lot
