### ISSUE TITLE
ToDo Liste

### ISSUE THREAD

**Issue by J0hnHawk** [J0hnHawk/FS17_WebStats#31]
Okay, damit ich nichts vergesse - nebenbei spiele ich ja auch noch ;-) - eine ToDo Liste:
Wünsche und Anregungen gern ergänzen.

- ~~map.txt für alle Karten-Konfigurationen anpassen~~ (05a78448e8623b59f13a51f79bcc88c79217fc30) und/oder ~~loadConfig.php robuster programmieren.~~ (244b59ea90bbef6f2c740031261abc7400a012ff)
- Preisübersicht um Optionen zum ein/ausblenden von Verkaufsstellen und evtl. Waren erweitern
- fehlende Übersetzungen auf der NF Marsch 4fach ergänzen (Paletten des Grundspiels sind noch nicht vollständig)
- fehlende Übersetzungen auf den original Karten (Goldcrest Valley und Sosnovka) ergänzen (Paletten des Grundspiels sind noch nicht vollständig)
- Support für Südamerika-Karte? (ich hab das DLC nicht)
- Tagesbedarf von Rohstoffen im Nachfragebereich der Warendetailseite ergänzen.
- potentieller Verkaufserlös auf der Warendetailseite anzeigen?
- ~~Produktion von weiteren Paletten in den Viehställen~~ (efe26d0e670d31371d4e078585d3e14c462a786f)

**Comment by alex83we** [comment]
ich habe das Platinum ADDON aber leider kann ich die karte nicht Exportieren da es die nicht so gibt wie die 2 Standard Maps :-(

**Comment by J0hnHawk** [comment]
Wenn, dann dürfte das höchstens über den Giants Editor funktionieren. Keine Ahnung ob das schon ans "Raubkopieren" grenzt. Lassen wir das lieber. :-D

Ich hab "deine Ferkel" rein programmiert. Mit dem Spielstand, den du mir gegeben hast, funktioniert es. 
`<output name="pigletBox" production_factor="24" capacity="5" fillType="pigletBox" palettArea="122 -39 123 -36" palettPlaces="6" showInStorage="false" />`
`<productivity name="wholeGrain" factor="4.8" />`
Diese beiden Zeilen habe ich zum Testen im 'Animals_pig' Teil ergänzt. Die Attribute sind aber nur kopiert von anderen Zeilen. Die musst du noch anpassen.

**Comment by J0hnHawk** [comment]
Ich mach aus der gesammelten ToDo Liste doch lieber wieder einzelne "Issues". Das lässt sich einfacher händeln.
