### ISSUE TITLE
ksort()

### ISSUE THREAD

**Issue by alex83we** [J0hnHawk/FS17_WebStats#32]
Warning: ksort() expects parameter 1 to be array, null given in D:\xampp\htdocs\include\prices.php on line 26

Sobald keine TipTrigger vorhanden sind kommt oben genannte Fehlermeldung

**Comment by J0hnHawk** [comment]
Oups. Beim Umstellen des Arraynamens hab ich die Definition vergessen abzuändern. Danke.
Die Meldung sollte verschwunden sein.
