### ISSUE TITLE
loadConfig.php / function.php

### ISSUE THREAD

**Issue by alex83we** [J0hnHawk/FS17_WebStats#35]
Er lädt leider nur die NFM29 die anderen Maps werden nicht geladen :-(

siehe http://test.farming-sim.de

------------------------------------------------------------------------------------------------------------

Fehler gefunden      Zeile 162 map.txt > map.cfg 
                                und Zeile 177 das gleiche

des weiteren liest er die map.cfg nicht richtig aus er zeigt nur die erste zeile bei mod map an

**Comment by J0hnHawk** [comment]
Beim Überpüfen des Installationsprozesses war ich noch nicht wieder angekommen.  Ich hab die Funktionen jetzt angepasst. Nun sollte es wieder funktionieren.

**Comment by alex83we** [comment]
werde es mal probieren und gebe dir feedback

**Comment by alex83we** [comment]
Funktioniert Danke für den schnellen fix
