### ISSUE TITLE
Hintergrundbild FS17 Theme

### ISSUE THREAD

**Issue by alex83we** [J0hnHawk/FS17_WebStats#36]
Ist es möglich das du das bild fixierst mit background-attachment: fixed; da sich das bild wiederholt sobald es über das normale Fenster hinaus geht. 
und eventuell eine leichte Transparenz einbauen das würde sicher gut aussehen so ungefähr rgba(46,46,46,0.75) würde ich machen.

**Comment by J0hnHawk** [comment]
Hehe, ich bin zur Zeil zum Testen mit der Map Goldcrest Valley unterwegs. Da ist so wenig verbaut, dass immer alles auf eine Seite passt. Wiederholen tut sich das Bild da nicht :-D

Aber du hast recht. Sieht blöd aus mit sich wiederholendem Bild.

**Comment by alex83we** [comment]
ja das dachte ich mir am besten auch gleich noch mittig ausrichtigen so dass sich das Bild immer von der Mitte her ausrichtet

background-position: center center;
so wird es immer mittig ausgerichtet da die Seite ja Responsiv ist oder du blendest Bild ab einer bestimmten Größe aus

**Comment by J0hnHawk** [comment]
Ich hab die Zentrierung und Fixierung eingebaut. Die Transparenz gefiel mir nicht so. Ich hab die auskommentiert drin gelassen. Kannst du bei dir ja tauschen.
Ich hätte gern lieber einen transparenten Rahmen um die Fenster wie im Spiel. Aber darum kümmere ich mich später mal.
