### ISSUE TITLE
Liquid Manure at the animals isn't unlimited

### ISSUE THREAD

**Issue by J0hnHawk** [J0hnHawk/FS17_WebStats#42]
The stock of manure and manure in pigs and cows isnt unlimited. (Everyone has their limit)
(Submitted by JanSe)

Auf der Karte Goldcrest Valley hat der 'liquidManureTank' bei Kühen und Schweinen ein Fassungsvermögen von 800.000 Litern.

**Comment by alex83we** [comment]
ich habe jetzt mehrere Karten durchschaut und Configs erstellt und bei allen Maps ist bei 800.000 l Gülle der Tank voll.

**Comment by J0hnHawk** [comment]
Ich denke, die Kartenersteller werden sich da keinen Kopf gemacht haben und den Gülletank von Giants kopiert haben. Entsprechend wird das in der Regel überall 800.000 l sein.
Weißt du, wie das beim Mist ist? Im Editor hab ich auf die Schnelle nichts gefunden.

**Comment by alex83we** [comment]
Nein ich denke da gibt es keine Begrenzung weil der ja als  Haufen ausgegeben wird ich denke ehr das, das unser vor Redner meint

**Comment by ghost** [comment]
Liquid Manure = 800 000.
Manure = ∞
Thanks JanSe

**Comment by J0hnHawk** [comment]
Okay. Bug fixed :-)
If you created an own map configuration you need to add ` capacity="800000"` to liquidManure output in the animals section.
Oh, and you need to replace the savegame.php with the new one.
