### ISSUE TITLE
Animals in one Column (mobile)

### ISSUE THREAD

**Issue by J0hnHawk** [J0hnHawk/FS17_WebStats#43]
Browsing in the mobile web Animals Site in One Column.
(Submitted by JanSe)

**Comment by alex83we** [comment]
Habe da eine unschöne entdeckung gemacht in der mobilen ansicht

![screenshot_74](https://user-images.githubusercontent.com/10686163/35236201-b8f05cc4-ffa6-11e7-8510-1e165466211b.png)

**Comment by J0hnHawk** [comment]
Mit welchem Browser und Gerät ist das so?
Ich hab in 3 Browsern (Firefox, Chrome und Edge) auf dem PC und 2 Browsern auf dem Smartphone (Chrome und Firefox) getestet. Überall sieht die Viehseite "schön" aus. 
Dafür sehen alle anderen Seiten im Hochkantformat doof aus. Im Querformat geht es halbwegs.

**Comment by alex83we** [comment]
auf meinem smartphone und im crome sieht es genau so aus das die wolle überall angezeigt wird

**Comment by J0hnHawk** [comment]
Ach die Wolleeeeee..... :-)
Ich dachte du meinst das Design an sich, weil die Menüleiste den oberen Teil überdeckt.

**Comment by alex83we** [comment]
nein musste ja scrollen damit es ins bild passt irgendwan kommt auch ein 27" Monitor an die grenzen :-)

**Comment by J0hnHawk** [comment]
Nu aber ;-)

**Comment by alex83we** [comment]
ja so ist schön und jetzt in der mobilen Ansicht die navbar nich mehr fixieren wäre ein traum :-)

**Comment by J0hnHawk** [comment]
Ich würde dies Thema hier gerne schließen und setze die Navbar mit auf die Agenda für die Überarbeitung der mobilen Seiten. Denn hochkand sehen die wenigsten Seiten gut aus.
