### ISSUE TITLE
Next suggestions for improvement

### ISSUE THREAD

**Issue by ghost** [J0hnHawk/FS17_WebStats#48]
Hi,
Actual number of users viewing statistics in the footer.

Thanks JanSe

**Comment by J0hnHawk** [comment]
Should be no problem.

**Comment by ghost** [comment]
thanks

**Comment by J0hnHawk** [comment]
Let us open this topic again until i build it in ;-)

**Comment by J0hnHawk** [comment]
I need some czech translation... ;-)

USER_ONLINE=Visitor online
HIDE_FOOTER=Hide footer

**Comment by ghost** [comment]
USER_ONLINE=Návštěvník online
HIDE_FOOTER=Skrýt zápatí

:)

**Comment by alex83we** [comment]
Muss der Footer fixiert sein, reicht es nicht, wenn er sich immer unten ausrichtet.
Ich persönlich finde es schöner wenn der Footer nicht fixiert ist, da er ja in deinem Fall schon recht groß ist. 
Wenn der Footer nicht so groß wäre würde das nix machen, und man sollte auch an die User denken die sich die Seite mobil ansehen.
Denn da sieht es leider dann sehr schrecklich aus und man kann kaum was erkennen die jetzige Version mit dem Footer ist für das Handy nur in Querformat sichtbar im Hochformat ist der footer leider unter der config.  
Und ich weiß sehr gut was es heißt Responsive Webseiten zu gestalten so dass sie in den gängigen Größen gut aussehen.

**Comment by J0hnHawk** [comment]
Eigentlich sollte der Footer auf dem Handy gar nicht sichtbar sein. Und auf meinem Handy ist das tatsächlich auch so - selbst im Querformat. Ich hab dem Footer ein "hidden-xs" verpasst. Andere Geräte habe ich nicht ausprobiert.
Fixiert habe ich ihn deshalb, weil ich es so verstanden habe, dass man  ja gerade wissen möchte, wie viele Leute sich die WebStats gerade ansehen. Daher sollte er auch immer sichtbar sein. 
Mich persönlich interessiert das nicht so, drum hab ich ihn als abschaltbar eingebaut. Auch das Fixieren könnte man über einen Schalter abschaltbar machen.

**Comment by alex83we** [comment]
na ja mir ist das auch nicht so wichtig den es Doppelt sich ja alles im Infofeld sieht man ja alles wichtige man könnte ja die User anzeige auch einfach in den Header schieben wenn es nur um die User geht und dort kann man dann ja mit einem Symbol arbeiten z.b: glyphicon glyphicon-user und dahinter die online User
