### ISSUE TITLE
Produktionsübersicht

### ISSUE THREAD

**Issue by alex83we** [J0hnHawk/FS17_WebStats#49]
ist es möglich das man den Input ausblendet in der Produktionsübersicht da es einige werte gibt die nur Fake sind zum beispiel die Klärgruben auf der Hof Bergmann

**Comment by J0hnHawk** [comment]
Ich denke das schon, dass das möglich wäre. In letzter Konsequenz könnte man sie einfach auf der HTML Seite nicht mit ausgeben. 
Funktionieren die Klärgruben ähnlich wie der Baumarkt auf der Karte NF Marsch? Da hat der Input ja zumindest noch halbwegs Sinn.

**Comment by alex83we** [comment]
na ja ich will ja schon die gülle sehen zum Beispiel denn wenn ich sie ausblende blendet er mir auch den Gülle wert aus und ich will auch sehen wenn die Klärgrube voll ist 

`  <item name="mCompanyFactory_slurryPit01" locationType="FabrikScript" ProdPerHour="50" position="-814.023 0 358.434" showInProduction="true" >
    <input name="slurryPit_fakeInput" capacity="5000" factor="0" fillTypes="water" showInStorage="false" />
    <output name="liquidManure" capacity="10000" factor="1" fillType="liquidManure" showInStorage="true" />
  </item>`

**Comment by J0hnHawk** [comment]
Ich schau mir das mal an.

**Comment by J0hnHawk** [comment]
Ich habe es eingebaut. Du kannst die "input" oder "output" Elemente jetzt um den Parameter "showInProduction" erweitern. Setzt du in auf "false" wird der fillType nicht ausgewertet. Lässt du den Parameter weg oder setzt ihn auf "true" wird er ausgewertet.

<input name="slurryPit_fakeInput" capacity="5000" factor="0" fillTypes="water" showInStorage="false" **showInProduction="false"** />

Schau mal, ob das so ok ist.

**Comment by alex83we** [comment]
Ja genau so ist das cool

**Comment by J0hnHawk** [comment]
Ok, dann schließe ich das Thema hier :-)

**Comment by alex83we** [comment]
Sorry muss nochmal das Thema aufgreifen cool wäre es wenn man das Template anpasst zum Beispiel wenn ich den Input ausblende das auch auf der Übersichtsseite der eintrag verschwindet wenn möglich 

![screenshot_73](https://user-images.githubusercontent.com/10686163/35226402-755ae3be-ff8b-11e7-88bf-2dc5471e2a40.png)

**Comment by J0hnHawk** [comment]
Oh, ja. Das sieht wirklich bescheiden aus.

**Comment by J0hnHawk** [comment]
Hab die Styles angepasst.

**Comment by alex83we** [comment]
Leider funktioniert der pull request nicht oder ich bin zu dumm dafür nutzte git erst seit dem Projekt

ich habe mal die production.tpl angepasst den da sah es auch ein wenig unschön aus das die Rohstoffe/Produkte noch da standen.


[styles.zip](https://github.com/J0hnHawk/FS17_WebStats/files/1654951/styles.zip)

und hier noch die CSS Anpassung einfach in die customstyle.css und fertig 

`
.table>tbody>tr:last-child {
	padding: 5px;
	line-height: 1.42857143;
	vertical-align: top;
	border-top: 1px solid #1c1e22
}
`

**Comment by J0hnHawk** [comment]
Ich steh mit Git(Hub) zum Teil auch noch auf Kriegsfuß. 
Ich schaue es mir an

**Comment by alex83we** [comment]
die styles Änderung macht leider kein sinn da sie dann die Produkte nach links schiebt wen mehr Produkte raus kommen als Rohstoffe rein gehen :-(

**Comment by J0hnHawk** [comment]
Ich hab noch nicht so ganz verstanden, was an den Styles auszusetzen war/ist?
Bei mir sieht es so aus (bei dir nicht?)
![screenshot-2018-1-25 nf marsch 4fach 1 3 webstats](https://user-images.githubusercontent.com/13779553/35386149-445662f6-01cb-11e8-81fd-cbb712d475bd.png)
![screenshot-2018-1-25 nf marsch 4fach 1 3 webstats 1](https://user-images.githubusercontent.com/13779553/35386152-472cbd90-01cb-11e8-8162-e205f3cf1d00.png)
![screenshot-2018-1-25 nf marsch 4fach 1 3 webstats 2](https://user-images.githubusercontent.com/13779553/35386157-4a8abb22-01cb-11e8-9d10-b8cc3b4d0829.png)
![screenshot-2018-1-25 nf marsch 4fach 1 3 webstats 3](https://user-images.githubusercontent.com/13779553/35386163-4ebcfc28-01cb-11e8-9e13-1e8bff6e0e14.png)

**Comment by alex83we** [comment]
Ja das ist okay so ich wollte es gerne so haben wie in der Detail Ansicht das das jeweils fehlende Produkt/Rohstoff ausgeblendet wird aber da rutscht dann auch der Rohstoff nach links wenn nur ein Produkt vorhanden ist daher ist das so okay wie es ist

Outlook for Android<https://aka.ms/ghei36> herunterladen

________________________________

**Comment by J0hnHawk** [comment]
Gut, dann schließe ich das Thema hier und vom der finalen Version 1.4 wieder ein Stück näher ;-)
