### ISSUE TITLE
Passwort Abfrage 

### ISSUE THREAD

**Issue by alex83we** [J0hnHawk/FS17_WebStats#50]
Ist es möglich das man die Änderung an den Einstellungen mit dem Passwort bestätigen muss.

**Comment by J0hnHawk** [comment]
Öhm, du meinst die Server-/Spielstandseinstellungen um die Karte oder den Server/Spielstand zu wechseln?

**Comment by alex83we** [comment]
Nein ich meine wenn ich eine Einstellung anpassen will zum Beispiel null Bestände an oder ausschalten das dann eine Sicherheitsabfrage kommt wo mann mit dem Passwort bestätigen muss

**Comment by J0hnHawk** [comment]
Da eine Passwortabfrage einzubauen macht, so wie es im Moment programmiert ist, keinen Sinn. 

Die Einstellungen werden in einem Cookie im Browser des Users gespeichert. Einstellungen die du tätigst haben keine Auswirkungen auf andere User. Ich hab das extra so programmiert, weil meine Mitspieler und ich die Webstats mit unterschiedlich einstellen wollen. 

Also, um die Eingangsfrage zu beantworten: Ja, es wäre möglich. Wenn es in anderen Servergemeinschaften gewünscht ist, dass alle Benutzer immer das gleiche angezeigt bekommen, könnte man Standardeinstellungen festlegen und dann unveränderbar machen. Aber is es wirklich nötig?
