### ISSUE TITLE
 FarmSiloSystem 1.1.0.0 Mod

### ISSUE THREAD

**Issue by J0hnHawk** [J0hnHawk/FS17_WebStats#51]
Ich wollte gerade eine Karte einbauen aber scheitere an dem FarmSiloSystem da dies das einzige SiloSystem ist was auf der Karte verbaut ist vielleicht schaust du dir das mal bei gelegenheit an so das auch dies eventuel als Lager genutzt werden kann hier mal ein link https://ls-modcompany.com/filebase/file/47-farmsilosystem/
(gemeldet von alex83we)

**Comment by J0hnHawk** [comment]
Kannst du mir einen Spielstand damit zukommen lassen oder die entsprechenden Einträge aus der vehicle.xml hier kopieren?

**Comment by alex83we** [comment]
Ich glaube da ist es besser diesen Mod mal anzuschauen denn das System gibt es als Plazierbaremod und zum einbauen in die Karte.

`<onCreateLoadedObject saveId="FarmSiloSystem08">
        <FillLevel fillType="1" Lvl="1000000"/>
        <FillLevel fillType="2" Lvl="1000000"/>
        <FillLevel fillType="3" Lvl="1000000"/>
        <FillLevel fillType="4" Lvl="1000000"/>
        <FillLevel fillType="5" Lvl="1000000"/>
        <FillLevel fillType="6" Lvl="1000000"/>
    </onCreateLoadedObject>`

**Comment by J0hnHawk** [comment]
Okay, das ähnelt dem FabrikScript nur das die "Rohstoff"/"Produkt" Elemente schlicht "FillLevel" heißen.
Die "fillType"-Attribute sind aber nicht einfach schlicht durchnummeriert, oder? Tatsächlich stehen da dann doch "wheat", "barley" usw drin?

**Comment by alex83we** [comment]
nein sie sind nummeriert das ist ja das Problem mann müsste die als Lager komplett neu einbinden und auslesen lassen nicht wie bisher `'storage'` sondern in dem fall mit `'FarmSiloSystem'` beispielsweise und die füllTypen sind immer gleich ich denke `fillType 1 = Weizen fillType 2 = Gerste` usw. in dem Silo sind nur die 6 Standardfrüchte mehr kann man da nicht einlagern

**Comment by alex83we** [comment]
Hier ein Auszug aus der lua 

`self.materials = {};
	self.materials[FillUtil.fillTypeNameToInt["wheat"]] = getMaterial(self.inputMove.movingId2, 0);
	self.materials[FillUtil.fillTypeNameToInt["barley"]] = getMaterial(self.inputMove.movingId2, 1);
	self.materials[FillUtil.fillTypeNameToInt["rape"]] = getMaterial(self.inputMove.movingId2, 2);
	self.materials[FillUtil.fillTypeNameToInt["sunflower"]] = getMaterial(self.inputMove.movingId2, 4);
	self.materials[FillUtil.fillTypeNameToInt["soybean"]] = getMaterial(self.inputMove.movingId2, 5);
	self.materials[FillUtil.fillTypeNameToInt["maize"]] = getMaterial(self.inputMove.movingId2, 3);`

**Comment by J0hnHawk** [comment]
Okay. Ich frage mich zwar warum man den umständlichen Weg über eine Mappingtabelle geht anstatt direkt die Fruchtsorten ins Savegame zu schreiben aber mein Programm ist bestimmt auch nicht das Gelbe vom Ei.
Du hast Recht, da da werde ich in der savegame.php extra eine Abfrage mit zusätzlichem Programmcode einbauen müssen... ich fang' mal an.

**Comment by alex83we** [comment]
Das ist ebend die LS-Modcompany die wollen ebend das nicht jeder ihre Mods umbauen kann weil sich kein moder an die LUA traut sondern nur den Standard von Giants kann

**Comment by J0hnHawk** [comment]
So, ich hab da mal was gebastelt. Ich hatte die Idee, dass Mods eigene PHP Scripte mitbringen könnten schon länger im Hinterkopf. Bisher hab ich das noch nicht für nötig gehalten. Jetzt hab' ich es doch eingebaut. 
Kartenobjekten oder Mods können nun eigene PHP Scripte beigefügt werden um Daten aus dem Savegame auszulesen.

@alex83we: Du musst die beiden Dateien FarmSiloSystem.xml und FarmSiloSystem.php in den Kartenordner verschieben da das Farmsilosystem auf deiner Karte fest verbaut ist. 

Probier mal, ob es bei dir auch klappt.

**Comment by alex83we** [comment]
Leider klappt das nicht oder ich bin zu doof es einzubauen denn das Silo muss auf der map als 'storage' sein.

**Comment by J0hnHawk** [comment]
Ne, der locationType darf nicht mehr "storage" sein. Sonst wird das zusätzliche Script nicht geladen. 

Wenn du in deiner Konfiguration noch irgendwo sowas hier hast:
`<item name="FarmSiloSystem08" locationType="storage" position="x y z" />`
dann lösch das mal oder kommentiere es aus. Klappt es dann?

Ich habe deinen Schnipsel:
`<onCreateLoadedObject saveId="FarmSiloSystem08"> <FillLevel fillType="1" Lvl="1000000"/> <FillLevel fillType="2" Lvl="1000000"/> <FillLevel fillType="3" Lvl="1000000"/> <FillLevel fillType="4" Lvl="1000000"/> <FillLevel fillType="5" Lvl="1000000"/> <FillLevel fillType="6" Lvl="1000000"/> </onCreateLoadedObject>`
in ein Savegame von mir rein kopiert. Zusätzlich zum normalen Farmsilo (wobei letzeres egal ist) und es hat funktioniert.

**Comment by alex83we** [comment]
~bei mir funktioniert das leider nicht er gibt keine Lagerbestände aus in der Lagerübersicht und auch die Waren werden nicht erweitert.~

Nachdem ich nun heute deine komplette Konfiguration (WebStats Komplett) übernommen habe funktioniert auch das FarmSilo

**Comment by J0hnHawk** [comment]
Schön. 
Komplette Konfiguration? Meinst du die Kartenkonfigurationen oder hattest du eine der PHP Dateien nicht übernommen?

**Comment by alex83we** [comment]
ich meine die Komplette konfiguration
