### ISSUE TITLE
Lagermöglichkeit in Fahrsilos

### ISSUE THREAD

**Issue by J0hnHawk** [J0hnHawk/FS17_WebStats#52]
In Mod Maps können auch andere Waren außer Häckselgut eingelagert werden.
<onCreateLoadedObject saveId="BunkerSilo_cowSilo" state="0" fillLevel="0" compactedFillLevel="0" fermentingTime="0" openedAtFront="false" openedAtBack="false" **inputfilltype="grassilageraw"**/>
(gemeldet von alex83we)

**Comment by J0hnHawk** [comment]
Den "inputfilltype" bei den Fahrsilos auszuwerten dürfte auch nicht das große Ding sein. Das würde ich aber nur einbauen, wenn es sich auch lohnt. Das heißt, wenn am Ende auch etwas anderes als Silage heraus kommt oder man das Fahrsilo als Lager "missbraucht" -also den Rohstoff, den man einlagert auch wieder heraus nimmt. 
Frag mal bitte deinen "Kartenkonfigurationsauftraggeber" ;-)

**Comment by J0hnHawk** [comment]
Ein schneller Workaround in der savegame.php wäre:
`            if (isset($object['inputfilltype'])) {
                $fillType = $object['inputfilltype'];
            } elseif ($state < 2) {
                $fillType = 'chaff';
            } else {
                $fillType = 'silage';
            }
`
Dies mit den Zeilen 229ff in der savegame.php

**Comment by alex83we** [comment]
es sind auf der Map beide typen verbaut das heißt ein Silo kann chaff aufnehmen das andere grassilage der Mapersteller wurde gefragt warte auf antwort

**Comment by alex83we** [comment]
ich werde es mal so für ihn einbauen und denke wenn man es wo anders benötigt kann man das ja individuell nachtragen 

![screenshot_70](https://user-images.githubusercontent.com/10686163/35221394-43673b2a-ff7a-11e7-90c2-25c06a931e39.png)

**Comment by alex83we** [comment]
Grassilage läuft über einen extra Mod der das dann einträgt in die Silo. Also wenn man Grassilage aktiviert hat, kann man zwischen Häckselgut -> Silage oder Grassilage (roh) -.> Grassilage wählen. Wenn man Grassilag enicht aktiviert wird aus dem Gras was man reinkippt Häckselgut.

**Comment by J0hnHawk** [comment]
Ein anderes Endprodukt... diese Lösung müsste funktionieren:
`        case 'bunker':
            // Fahrsilos
            $state = intval($object['state']);
            $fillLevel = intval($object['fillLevel']);
            if (isset($object['inputfilltype'])) {
            	$siloFillType=array('Grassilage (roh)','Grassilage');
            } else {
            	$siloFillType=array('chaff','silage');
            } 
            if ($state < 2) {
            	$fillType = $siloFillType[0];
            } else {
            	$fillType = $siloFillType[1];
            }
            addCommodity($fillType, $fillLevel, $location);
            break;
`
Die Zeile 
`$siloFillType=array('Grassilage (roh)','Grassilage');`
musst du noch auf die internen Werte anpassen.

Gefallen tut mir diese Lösung aber nicht. Das ist viel zu modspezifisch. Und eigentlich möchte ich die spezifischen Sachen aus dem eigentlich Programmcode heraushalten. Sinnvoll wäre es wohl, den Schnipsel in ein eine extra Datei auszulagern und wie beim Farmsilosystem (#51) nachzuladen. 
Aus `<item name="name" locationType="bunker" position="x y z" />` würde dann `<item name="name" locationType="extraFilePHP" scriptFile="php_script_xy.php" position="x y t" />`

**Comment by alex83we** [comment]
ich binde das in dem fall in die savegame ein da er nur die eine konfig hat da passt das

**Comment by J0hnHawk** [comment]
Als Mod mit zusätzlicher PHP Datei funktioniert es.
![grasssilage](https://user-images.githubusercontent.com/13779553/35235027-48e52840-ffa3-11e7-855f-5c0d8480a575.PNG)

Hier die PHP Datei und beispielhaft die geänderten Bunker für NF Marsch.
[grassSilageMod.zip](https://github.com/J0hnHawk/FS17_WebStats/files/1652957/grassSilageMod.zip)

Das Ganze ist aber auch erst nur ein erster Wurf, da man für den Mod dann immer noch die Kartenkonfiguration ändern muss (aber wenigstens nicht mehr den eigentlich Programmcode).

**Comment by alex83we** [comment]
das problem ist aber jetzt mit der variante das er leider alle silos auf grassilage stellt und wenn silos standard sind macht er fehler beim häckselgut :-( mit dem workaround funktioniert das ohne fehler

**Comment by J0hnHawk** [comment]
Was kommt denn da für eine Fehlermeldung? 
In der Theorie unterscheiden sich der Workaround aus meinem Posting vom Montag und der Mod in der Zip-Datei nicht. Beim Workaround wird auch bei jedem Bunker nach Grassilage gesucht.

**Comment by alex83we** [comment]
Die bunker funktionieren nun seit deinem update mit dem Fix wenn keine Lagerbestand vorhanden ist danke und er stellt auch um von grassilageraw > grassilage

Thema erfüllt und kann geschlossen werden

**Comment by J0hnHawk** [comment]
Super :-)
