### ISSUE TITLE
BGA/BioGas Anlage

### ISSUE THREAD

**Issue by alex83we** [J0hnHawk/FS17_WebStats#53]
BGA zeigt mir immer bunkerFillLevel an.

`<item name="Bga" locationType="bga" ProdPerHour="1000" position="-689.226 0 -640.372" showInProduction="true" isSellingPoint="true" >
    <input name="silage" capacity="50000" factor="360" fillTypes="bunkerFillLevel" showInStorage="false" />
    <input name="straw" capacity="50000" factor="360" fillTypes="bunkerFillLevel" showInStorage="false" />
    <input name="dryGrass_windrow" capacity="50000" factor="360" fillTypes="bunkerFillLevel" showInStorage="false" />
    <input name="grassilage" capacity="50000" factor="360" fillTypes="bunkerFillLevel" showInStorage="false" />
    <input name="manure" capacity="50000" factor="360" fillTypes="bunkerFillLevel" showInStorage="false" />
    <input name="beetPulp" capacity="50000" factor="360" fillTypes="bunkerFillLevel" showInStorage="false" />
    <input name="grass_windrow" capacity="50000" factor="360" fillTypes="bunkerFillLevel" showInStorage="false" />
    <input name="liquidManure" capacity="50000" factor="180" fillTypes="liquidManureFillLevel" showInStorage="false" />
    <output name="digestate" capacity="800000" factor="87" fillTypes="digestateSiloFillLevel" showInStorage="true" />
  </item>`

Screenshots

![screenshot_71](https://user-images.githubusercontent.com/10686163/35221462-82007d24-ff7a-11e7-9b20-907f94e4a637.png)
![screenshot_72](https://user-images.githubusercontent.com/10686163/35221463-821c8014-ff7a-11e7-881e-edd688cb2e9f.png)

**Comment by J0hnHawk** [comment]
Hm, vom Programm her richtig. Vermutlich hast du den fillType "bunkerFillLevel" noch nicht in "Silage" übersetzt. 
Aber auch das würde zu Problemen führen, da beim "straw"-Trigger der fillType auch "bunkerFillLevel" ist. 
Wie sieht denn der entsprechende Abschnitt im Savegame aus?

**Comment by alex83we** [comment]
` <onCreateLoadedObject saveId="Bga" digestateSiloFillLevel="51150.004502296" bunkerFillLevel="0" liquidManureFillLevel="0">
        <tipTrigger>
            <stats fillType="dryGrass_windrow" received="0" paid="0" isInPlateau="false" nextPlateauNumber="0" meanValue="0" plateauDuration="51840000" plateauTime="0" >
                <curveBaseCurve amplitudeDistribution="2" periodDistribution="1" nominalAmplitude="0.028799999505281" nominalAmplitudeVariation="0.021600000560284" nominalPeriod="172800000" nominalPeriodVariation="64800000" amplitude="0.015228236094117" period="85916576" time="85248107.370003" />
                <curve1 amplitudeDistribution="1" periodDistribution="1" nominalAmplitude="0.014399999752641" nominalAmplitudeVariation="0.0028800000436604" nominalPeriod="604800000" nominalPeriodVariation="120960000" amplitude="0.014244753867388" period="403378592" time="370879635.37" />
            </stats>
            <stats fillType="silage" received="120500" paid="79131.3671875" isInPlateau="true" nextPlateauNumber="0" meanValue="0" plateauDuration="51840000" plateauTime="15264765.91436" >
                <curveBaseCurve amplitudeDistribution="2" periodDistribution="1" nominalAmplitude="0.14699999988079" nominalAmplitudeVariation="0.11025000363588" nominalPeriod="172800000" nominalPeriodVariation="64800000" amplitude="0.19830860421674" period="43463449.739032" time="10865862.434758" />
                <curve1 amplitudeDistribution="1" periodDistribution="1" nominalAmplitude="0.073499999940395" nominalAmplitudeVariation="0.014700000174344" nominalPeriod="604800000" nominalPeriodVariation="120960000" amplitude="0.086331561207771" period="546242368" time="109834668.19286" />
            </stats>
            <stats fillType="straw" received="0" paid="0" isInPlateau="false" nextPlateauNumber="1" meanValue="0" plateauDuration="51840000" plateauTime="0" >
                <curveBaseCurve amplitudeDistribution="2" periodDistribution="1" nominalAmplitude="0.024599999189377" nominalAmplitudeVariation="0.018449999392033" nominalPeriod="172800000" nominalPeriodVariation="64800000" amplitude="0.0076849046163261" period="69907872" time="33248464.344658" />
                <curve1 amplitudeDistribution="1" periodDistribution="1" nominalAmplitude="0.012299999594688" nominalAmplitudeVariation="0.0024600001052022" nominalPeriod="604800000" nominalPeriodVariation="120960000" amplitude="0.012593727558851" period="560801920" time="158082984.34466" />
            </stats>
            <stats fillType="liquidManure" received="0" paid="0" isInPlateau="true" nextPlateauNumber="0" meanValue="0" plateauDuration="51840000" plateauTime="7037845.2412949" >
                <curveBaseCurve amplitudeDistribution="2" periodDistribution="1" nominalAmplitude="0.019799999892712" nominalAmplitudeVariation="0.014849999919534" nominalPeriod="172800000" nominalPeriodVariation="64800000" amplitude="0.0058312313346725" period="93874104.419819" time="23468526.104955" />
                <curve1 amplitudeDistribution="1" periodDistribution="1" nominalAmplitude="0.0098999999463558" nominalAmplitudeVariation="0.001979999942705" nominalPeriod="604800000" nominalPeriodVariation="120960000" amplitude="0.0087303798645735" period="508159328" time="279018652.31172" />
            </stats>
            <stats fillType="manure" received="0" paid="0" isInPlateau="false" nextPlateauNumber="1" meanValue="0" plateauDuration="51840000" plateauTime="0" >
                <curveBaseCurve amplitudeDistribution="2" periodDistribution="1" nominalAmplitude="0.019799999892712" nominalAmplitudeVariation="0.014849999919534" nominalPeriod="172800000" nominalPeriodVariation="64800000" amplitude="0.0094105014577508" period="76348784" time="19159456.266432" />
                <curve1 amplitudeDistribution="1" periodDistribution="1" nominalAmplitude="0.0098999999463558" nominalAmplitudeVariation="0.001979999942705" nominalPeriod="604800000" nominalPeriodVariation="120960000" amplitude="0.0092931622639298" period="540395264" time="25453332.266432" />
            </stats>
            <stats fillType="beetPulp" received="0" paid="0" isInPlateau="true" nextPlateauNumber="1" meanValue="0" plateauDuration="51840000" plateauTime="43152192.08242" >
                <curveBaseCurve amplitudeDistribution="2" periodDistribution="1" nominalAmplitude="0.30000001192093" nominalAmplitudeVariation="0.22499999403954" nominalPeriod="172800000" nominalPeriodVariation="64800000" amplitude="0.20239931344986" period="94002944" time="70502208" />
                <curve1 amplitudeDistribution="1" periodDistribution="1" nominalAmplitude="0.15000000596046" nominalAmplitudeVariation="0.029999999329448" nominalPeriod="604800000" nominalPeriodVariation="120960000" amplitude="0.16174121201038" period="577589568" time="222608255.53709" />
            </stats>
            <stats fillType="grass_windrow" received="0" paid="0" isInPlateau="true" nextPlateauNumber="0" meanValue="0" plateauDuration="51840000" plateauTime="24320452.495857" >
                <curveBaseCurve amplitudeDistribution="2" periodDistribution="1" nominalAmplitude="0.027000000700355" nominalAmplitudeVariation="0.020250000059605" nominalPeriod="172800000" nominalPeriodVariation="64800000" amplitude="0.010785087461155" period="52025063.12323" time="13006265.780807" />
                <curve1 amplitudeDistribution="1" periodDistribution="1" nominalAmplitude="0.013500000350177" nominalAmplitudeVariation="0.0027000000700355" nominalPeriod="604800000" nominalPeriodVariation="120960000" amplitude="0.013386055827141" period="521029120" time="294068336.91225" />
            </stats>
        </tipTrigger>
    </onCreateLoadedObject>`

**Comment by J0hnHawk** [comment]
Meine Aussage von heute Nachmittag ziehe ich zurück... zumindest teilweise. Das Programm funktioniert aber so wie es soll - bei mir wenigstens.
Ich habe jetzt zum Testen deine Konfiguration der BGA 1:1 übernommen. Und in meinem Savegame die BGA-Daten mit deinen ersetzt.
![stroh](https://user-images.githubusercontent.com/13779553/35234067-3566397e-ffa0-11e7-820e-72a2b0552be7.PNG)
![silage](https://user-images.githubusercontent.com/13779553/35234096-43420d16-ffa0-11e7-99ac-d28673783be3.PNG)
![produktion](https://user-images.githubusercontent.com/13779553/35234077-3c1baab0-ffa0-11e7-8f4a-c1e552a488f7.PNG)
![fabrik](https://user-images.githubusercontent.com/13779553/35234083-3e8d952e-ffa0-11e7-8dff-0ee612c5770b.PNG)

Ich befürchte, da muss irgendwo eine Fehler in deiner Konfiguration stecken. Eigentlich sollte der bunkerFillLevel auch nicht bei den Rohstoffen auftauchen.

**Comment by alex83we** [comment]
ich übernehme deine BGA der NFM

**Comment by J0hnHawk** [comment]
Öhm, ich hab deine übernommen :-D
Ich hab meine, womit ich die Screenshots oben erstellt habe, in dem Thema Lagermöglichkeit in Fahrsilos #52 angehängt.

**Comment by alex83we** [comment]
kann es sein das die BGA von den Tieren abhänig ist ?

**Comment by J0hnHawk** [comment]
Nein, grundsätzlich nicht. Was sein könnte ist, dass du gleich Übersetzungen verwendet hast wo du keine gleichen Übersetzungen verwenden dürftest oder sich vielleicht die Triggerbezeichnungen überschneiden? Das ist ne Kartenkonfiguration bei der auch mehrere Mods verwendet werden, oder?

Was auch sein könnte, hast du den bunkerFillLevel in irgend einem Lager oder bei den Tieren mit angegeben? Denn irgendwo findet mein Programm eine Lagermöglichkeit für bunkerFillLevel.

**Comment by alex83we** [comment]
nein habe gerade an meiner aktuellen karte probiert da kam liquidManureFillLevel und ich habe die tiere eingefügt und die liquidManureFillLevel war weg irgendwo sind da doch abhängigkeiten. zeile 350 in der Savegame.php verweist auf liquidManureFillLevel

**Comment by J0hnHawk** [comment]
Da (Zeilen 347 und 348 bei mir) wird der Gülle- und Mistbestand ermittelt. Beides soll dann ja auch in die Lagerübersicht. Der bunkerFillLevel hingegen sollte grundsätzlich nur in den Zeilen 253 für die BGA ausgelesen werden und das auch nur als Wert.

**Comment by J0hnHawk** [comment]
Ich muss da wohl mal kleine Brötchen backen...
Ich habe den Fehler gefunden - doch im Programm. In der savegame.php werden am Ende die 'combineFillType' ermittelt. Da wird der bunkerFillLevel hinzugefügt - was er nicht sollte. 'Nen Fix gibt es morgen.

Was ich nur nicht verstehe ist, das der Fehler nicht immer auftritt. :-(

**Comment by alex83we** [comment]
Ich freu mich drauf

**Comment by J0hnHawk** [comment]
Kleiner Zwischenstand:
Ich hab es noch nicht hinbekommen das es komplett richtig funktioniert. Mal geht das eine, dann wieder das andere nicht. Die Silage wird als Kombinationsrohstoff erkannt weil Trigername und fillType abweichen. Darum wird bunkerFillType zu den Waren ergänzt, was dann zu den obigen Anzeigen führt. Bei Wasser zum Beispiel ist das aber auch so und da funktioniert es.

Ich hatte gestern nicht genug Ruhe am Stück um eine Lösung zu finden. Wahrscheinlich läuft es darauf hinaus, dass ich Name und fillType bei der BGA in der Konfig tausche. Aber 100%ig funktioniert es mit der Lösung wie gesagt auch noch nicht.

**Comment by J0hnHawk** [comment]
Manchmal kann eine Lösung so einfach sein. Ich hoffe sie funktioniert auch bei dir?

**Comment by alex83we** [comment]
ich habe immer noch die bunkerFillLevel ausgegeben:-(

**Comment by J0hnHawk** [comment]
Ich habe meine Tests mit der Sosnovka Konfiguration gemacht, jetzt eben aber auch noch mal mit dem Livedatenbestand auf unserem Dedi-Server, auf dem NF Marsch 4fach läuft.
Bei beiden tritt der Fehler nicht mehr auf. Ich habe heute noch ein paar Änderungen an der Erfassung der Waren/Produkte vorgenommen, die allerdings keine Auswirkungen mehr auf den bunkerFillLevel gehabt haben dürften. Bei mir hatte es auch schon vorher funktioniert.
Ich hatte oben angedeutet, Name und fillType bei der BGA zu tauschen. Das habe ich letztlich aber doch nicht getan, weil es viel mehr Änderungen nach sich gezogen hätte.
Hast du das in deinen Konfigurationen schon gemacht?

Meine Konfiguration für die BGA (Sonsnovka) sieht so aus:

`<?xml version="1.0" encoding="UTF-8"?>
<mapconfig>
	<item name="Bga" locationType="bga" ProdPerHour="1000" position="-646 0 -299" showInProduction="true" isSellingPoint="true">
 		<input name="silage" capacity="50000" factor="360" fillTypes="bunkerFillLevel" showInStorage="false" />
 		<input name="straw" capacity="50000" factor="360" fillTypes="bunkerFillLevel" showInStorage="false" />
		<input name="liquidManure" capacity="&#8734;" factor="180" fillTypes="liquidManureFillLevel" showInStorage="false" />
		<output name="digestate" capacity="800000" factor="87" fillTypes="digestateSiloFillLevel" showInStorage="true" />
	</item>
	<item name="BunkerSilo_silo1" locationType="bunker" position="428.9 0 -281.7" />
	<item name="BunkerSilo_silo2" locationType="bunker" position="279.0 0 843.7" />
	<item name="BunkerSilo_silo3" locationType="bunker" position="-641 0 -251" />
	<item name="BunkerSilo_silo4" locationType="bunker" position="-651 0 -251" />
	<item name="BunkerSilo_silo5" locationType="bunker" position="-661 0 -251" />
	<item name="BunkerSilo_silo6" locationType="bunker" position="-631 0 -251" />
	<item name="BunkerSilo_silo7" locationType="bunker" position="-621 0 -251" />
	<item name="BunkerSilo_silo8" locationType="bunker" position="-255.5 0 -794.0" />
	<item name="BunkerSilo_silo9" locationType="bunker" position="-445.3 0 234.5" />
	<item name="BunkerSilo_silo10" locationType="bunker" position="674.3 0 310.8" />
</mapconfig>
`

In der vehicle.xml des Spielstands sieht es so aus:
`    <onCreateLoadedObject saveId="Bga" digestateSiloFillLevel="0" bunkerFillLevel="0" liquidManureFillLevel="0">
        <tipTrigger>
            <stats fillType="liquidManure" received="0" paid="0" isInPlateau="true" nextPlateauNumber="1" meanValue="0" plateauDuration="51840000" plateauTime="45357149.648359" >
                <curveBaseCurve amplitudeDistribution="2" periodDistribution="1" nominalAmplitude="0.01188" nominalAmplitudeVariation="0.00891" nominalPeriod="172800000" nominalPeriodVariation="64800000" amplitude="0.010336659166195" period="78928795.197798" time="59196596.398348" />
                <curve1 amplitudeDistribution="1" periodDistribution="1" nominalAmplitude="0.00594" nominalAmplitudeVariation="0.001188" nominalPeriod="604800000" nominalPeriodVariation="120960000" amplitude="0.0068026007380419" period="514050765.15147" time="461783249.05951" />
            </stats>
            <stats fillType="manure" received="0" paid="0" isInPlateau="true" nextPlateauNumber="0" meanValue="0" plateauDuration="51840000" plateauTime="49378642.034591" >
                <curveBaseCurve amplitudeDistribution="2" periodDistribution="1" nominalAmplitude="0.01188" nominalAmplitudeVariation="0.00891" nominalPeriod="172800000" nominalPeriodVariation="64800000" amplitude="0.01175379337441" period="71599340.415986" time="17899835.103996" />
                <curve1 amplitudeDistribution="1" periodDistribution="1" nominalAmplitude="0.00594" nominalAmplitudeVariation="0.001188" nominalPeriod="604800000" nominalPeriodVariation="120960000" amplitude="0.0048483271257999" period="418547517.00149" time="312895793.69543" />
            </stats>
            <stats fillType="silage" received="0" paid="0" isInPlateau="true" nextPlateauNumber="0" meanValue="0" plateauDuration="51840000" plateauTime="9253881.3221795" >
                <curveBaseCurve amplitudeDistribution="2" periodDistribution="1" nominalAmplitude="0.0882" nominalAmplitudeVariation="0.06615" nominalPeriod="172800000" nominalPeriodVariation="64800000" amplitude="0.060593182493022" period="68157746.33694" time="17039436.584235" />
                <curve1 amplitudeDistribution="1" periodDistribution="1" nominalAmplitude="0.0441" nominalAmplitudeVariation="0.00882" nominalPeriod="604800000" nominalPeriodVariation="120960000" amplitude="0.045553466064829" period="456949489.6224" time="49842585.85545" />
            </stats>
            <stats fillType="straw" received="0" paid="0" isInPlateau="true" nextPlateauNumber="0" meanValue="0" plateauDuration="51840000" plateauTime="9253881.3221795" >
                <curveBaseCurve amplitudeDistribution="2" periodDistribution="1" nominalAmplitude="0.0882" nominalAmplitudeVariation="0.06615" nominalPeriod="172800000" nominalPeriodVariation="64800000" amplitude="0.060593182493022" period="68157746.33694" time="17039436.584235" />
                <curve1 amplitudeDistribution="1" periodDistribution="1" nominalAmplitude="0.0441" nominalAmplitudeVariation="0.00882" nominalPeriod="604800000" nominalPeriodVariation="120960000" amplitude="0.045553466064829" period="456949489.6224" time="49842585.85545" />
            </stats>
        </tipTrigger>
    </onCreateLoadedObject>
`
Das Stroh habe ich da rein editiert, um deine BGA mit den weiteren akzeptierten Fruchtsorten zu simulieren.

Die Ausgaben sehen dann so bei mir aus:
![screenshot-2018-1-25 sosnovka webstats](https://user-images.githubusercontent.com/13779553/35385949-6cd5fcec-01ca-11e8-8d59-06438d4e0811.png)
![screenshot-2018-1-25 sosnovka webstats 1](https://user-images.githubusercontent.com/13779553/35385953-71cb8ff0-01ca-11e8-8f1e-3e51bb14f22d.png)
![screenshot-2018-1-25 sosnovka webstats 2](https://user-images.githubusercontent.com/13779553/35385957-76b85f0c-01ca-11e8-91db-3766b7e17e89.png)
![screenshot-2018-1-25 sosnovka webstats 3](https://user-images.githubusercontent.com/13779553/35385960-79c82c68-01ca-11e8-8dcc-47f477770ab0.png)

**Comment by alex83we** [comment]
ich habe jetzt die fillTyps getauscht und es sieht aktuell gut aus 

![screenshot_81](https://user-images.githubusercontent.com/10686163/35392079-edd5c668-01e0-11e8-8098-63fc06d2d595.png)

![screenshot_80](https://user-images.githubusercontent.com/10686163/35392087-f8f38dc8-01e0-11e8-9b91-96178432552c.png)

so sieht es aus wenn bunkerFillLevel der fileTypes ist bei der karte 
![screenshot_79](https://user-images.githubusercontent.com/10686163/35392116-190bc594-01e1-11e8-91f6-eaa7dfdc6a42.png)

**Comment by J0hnHawk** [comment]
Du machst mich Wahnsinnig :-P
Die XML-Konfiguration, die du oben gepostet hast, dürfte eigentlich nicht funktionieren. Es sei denn, du hast auch in der savegame.php ein paar Sachen geändert. Das was ich bei dir bei GitHub sehe, sieht aber nicht danach aus.
Aber wenn's gut aussieht... never change a running system ;-)

**Comment by alex83we** [comment]
ich verändere an deinem code gar nix ich halte mich nur in der config auf bei allen anderen lasse ich nur dich ran da du den code kennst und ich keine lust habe mich da einzulesen :-) ich habe einen pull auf meinen server der immer die aktuelle version updatet und local habe ich auch immer deine aktuelle version

**Comment by J0hnHawk** [comment]
Das heißt, wir können das Thema hier abschließen?

**Comment by alex83we** [comment]
eigentlich nicht da der bunkerFillType nicht ausgelesen wird da ja die werte nun vertauscht sind :-( und er denn filtype ja nicht ermittelt aber probiere es mal wenn ich bunkerFillLevel mit dazu mache was dann passiert

**Comment by J0hnHawk** [comment]
Oh, ich glaube, dann hast du oben etwas überlesen. "name" und "fillTypes" müssen wie ursprünglich angegeben werden. Also so:
`<input name="silage" capacity="50000" factor="360" fillTypes="bunkerFillLevel" showInStorage="false" />`
Das heißt, wenn deine BGA mehr als nur Silage für den Bunker akzeptiert, musst du, wie du es ursprünglich auch gemacht hattest, für jede Ware eine eigene Zeile erstellen.

**Comment by alex83we** [comment]
ich habe jetzt alles noch mal auf einem frischen host gemacht und es gibt weiterhin diesen bunker aus 

![screenshot_102](https://user-images.githubusercontent.com/10686163/35444249-343849b4-02ae-11e8-9d37-0ac382519ad4.png)
![screenshot_103](https://user-images.githubusercontent.com/10686163/35444250-3459f406-02ae-11e8-8ad0-e77f2cd6957b.png)

**Comment by J0hnHawk** [comment]
Kannst du mir mal das komplette Savegame sowie die Kartenkonfiguration zippen, mit denen du die Screenshots erstellt hast. Und dann hier hochladen. Ich glaub nur so komm ich dem Übel auf die Spur.

**Comment by alex83we** [comment]
[savegame8.zip](https://github.com/J0hnHawk/FS17_WebStats/files/1668102/savegame8.zip)

[config.zip](https://github.com/J0hnHawk/FS17_WebStats/files/1668106/config.zip)

**Comment by alex83we** [comment]
das ist auch die einzige map wo das so passiert die morise land hat auch mehrere fillTyps und da geht es auch nur die map macht probleme

**Comment by J0hnHawk** [comment]
Ich glaube, jetzt hab' ich's wirklich. Die Rohstoffe bei der BGA werden jetzt beim Laden auch schon registriert. Dadurch müssen nicht mehr am Ende ermittelt werden. Möglicherweise kommt es darauf an, in welcher Reihenfolge das Spiel die Daten im Savegame abspeichert. Sodass der Anzeigefehler manchmal auftritt und manchmal nicht.

**Comment by alex83we** [comment]
okay jetzt sieht es gut danke dafür
