### ISSUE TITLE
Pallets loaded on the trailer are not displayed in the storage.

### ISSUE THREAD

**Issue by ghost** [J0hnHawk/FS17_WebStats#54]
Hello,
Pallets loaded on the trailer are not displayed in the storage.
Mods: http://sharemods.com/edflx98val86/FS17_M82_Trailer_UAL.zip.html
OR: http://sharemods.com/jrjsc32opcos/FS17_FlieglFlatbed_UAL.zip.html

Can it be added to show the palettes in the storage?
Thanks JanSe

savegames-vehicles = 24 pallets on the trailer (0 storage)

`<vehicle id="124" modName="FS17_M82_Trailer_UAL" filename="$moddir$FS17_M82_Trailer_UAL/M82Trailer.xml" isAbsolute="true" age="5" price="12100" propertyState="1" operatingTime="839.9502147913" foldAnimTime="0" dirtAmount="0.034925729148741" numBales="24" baleMode="6"><component1 position="784.19012451172 116.2692489624 -776.50061035156" rotation="-3.1395835876465 -0.16007150709629 -3.1413724422455"/><configuration name="attacherJoint" id="1"/><configuration name="wheel" id="2"/><boughtConfiguration name="attacherJoint" id="1"/><boughtConfiguration name="wheel" id="1"/><boughtConfiguration name="wheel" id="2"/><tensionBelt isActive="false"/><tensionBelt isActive="false"/><tensionBelt isActive="false"/><tensionBelt isActive="false"/><tensionBelt isActive="false"/><tensionBelt isActive="false"/><tensionBelt isActive="false"/><tensionBelt isActive="false"/><tensionBelt isActive="false"/><tensionBelt isActive="false"/><tensionBelt isActive="false"/><tensionBelt isActive="false"/><tensionBelt isActive="false"/><tensionBelt isActive="false"/><tensionBelt isActive="false"/><tensionBelt isActive="false"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="1"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="2"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="3"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="4"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="5"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="6"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="7"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="8"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="9"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="10"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="11"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="12"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="13"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="14"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="15"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="16"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="17"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="18"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="19"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="20"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="21"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="22"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="23"/><wool filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/palettezucker.i3d" fillLevel="3000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="24"/><wheelDirt wheel1="0.600000" wheel2="0.600000" wheel3="0.600000" wheel4="0.600000"/></vehicle>`

**Comment by J0hnHawk** [comment]
Mmpf. You found a next feature which i have planned but still not realized. 
Also bales on trailers are not displayed in storage... yet. :-D

**Comment by J0hnHawk** [comment]
Built in (1b0c69feb6d3f1d67da7e7046adbc357f4faaa35)

**Comment by ghost** [comment]
Please pallets of wood are not visible ... :( can you add? thank you

In trailer:
`<wood2 filename="$moddir$Thueringer_Oberland_V1_2/maps/modelle/Fabrik_Script/Paletten/boardPallet.i3d" fillLevel="4000" position="0 0 0" rotation="0 -0 0" wrappingState="0" baleValueScale="1" balePlace="1"/>`

**Comment by J0hnHawk** [comment]
I'll take a look into it

**Comment by J0hnHawk** [comment]
I changed the code to support more elements in xml structure of a trailer. I added "wood2". If there are more we can add them to the array in savegame.php. Later this could be moved to map config. Could you try out if it is working.

**Comment by ghost** [comment]
super works
thank you :)
