### ISSUE TITLE
Can animals be disallowed in the storage?

### ISSUE THREAD

**Issue by ghost** [J0hnHawk/FS17_WebStats#57]
Can animals be disallowed in the storage?
Not to show...

thanks :)

**Comment by J0hnHawk** [comment]
Hm, not that easy. All commodities are recorded in savegame.php. If you select e. g.  the option show only pallets, all other commodities would sorted out.
At the moment there is no posibillity to recognize if a commodity is an animal.
I'll take a look into it.

**Comment by J0hnHawk** [comment]
Build in and working in my tests.
I need a translation for "hide animals"

![screenshot-2018-1-25 nf marsch 4fach 1 3 webstats 4](https://user-images.githubusercontent.com/13779553/35389043-6c213846-01d6-11e8-9255-6eaf049c342c.png)

**Comment by ghost** [comment]
CZ translate
HIDE_ANIMALS=Skrýt zvířata

**Comment by alex83we** [comment]
wo kann man den die tiere aus blenden habe es nicht gefunden oder bin 
ich blind

okay gefunden war noch nciht aktuell die version :-)
