### ISSUE TITLE
Pfade der modMap

### ISSUE THREAD

**Issue by alex83we** [J0hnHawk/FS17_WebStats#58]
Leider werden die Pfade der Mod Map nicht mehr geladen

![screenshot_75](https://user-images.githubusercontent.com/10686163/35264522-5ba9f936-001d-11e8-8a26-1fa9679463d2.png)

**Comment by J0hnHawk** [comment]
Hab die Pfadübergabe in der Funktion angepasst. (f7942f88a5e55465626210f1af09ddf7b101d058)

**Comment by alex83we** [comment]
Super läuft wieder werde es auch mal wieder Schliessen
