### ISSUE TITLE
File template/overview.tpl not fully translated

### ISSUE THREAD

**Issue by ghost** [J0hnHawk/FS17_WebStats#59]
File template/overview.tpl not fully translated

Not translated:
Version
Spieler
Spielzeit
Position
ja
nein
Zur Zeit sind keine Spieler online.

thanks JanSe

I attach, my Czech translation of the application, please import. :)
[cz.zip](https://github.com/J0hnHawk/FS17_WebStats/files/1655356/cz.zip)

**Comment by J0hnHawk** [comment]
I do most of my tests in a locally savegame and in german. Yes i totally forgot the overview.tpl. 
I'll add it.
Thanks for the language file.

**Comment by ghost** [comment]
CZ translate:
PLAYER=Hráč
UPTIME=Čas online
ISADMIN=Admin
POSITION=Pozice
INVEHICLE=Ve vozidle
NOPLAYER=Momentálně není nikdo online.

thanks

**Comment by J0hnHawk** [comment]
Should be done. If the user language does not exists WebStats will now load the default language (currently german) to translate fruit types and so on.

**Comment by J0hnHawk** [comment]
I just updated the language file with your translations above ;-)

**Comment by ghost** [comment]
Version

no translate...

**Comment by ghost** [comment]
cz translate:
Version=Verze

**Comment by J0hnHawk** [comment]
You are right.
What is the czech word for 'Version'?
and there is another new translation 'NO_STOCKS' (german: Keine Lagerbestände)
It will be shown on commodity detail page if there is no stock for it.

**Comment by ghost** [comment]
Version=Verze
NO_STOCKS=Žádné zásoby

:)

**Comment by J0hnHawk** [comment]
Done :-)
I'm closing this topic now
