### ISSUE TITLE
Zusätzlicher Ordner

### ISSUE THREAD

**Issue by alex83we** [J0hnHawk/FS17_WebStats#60]
wäre es möglich das man in der config einen ordner anlegen kann wo ich z.b. nur änderungen ablegen kann.

Struktur:

> config/nfmarsch4f13/*.xml

und jetzt der zusätzliche Ordner

> config/nfmarsch4f13/ergaenzung/ergaenzung.xml

und eben die translate datei wäre für mapper gut dann können die ihre selber eingefügten Produktionen oder was auch immer ergänzen ohne an die haupt config zu müssen

**Comment by J0hnHawk** [comment]
Hm, haben wir das nicht schon so? Ich hab jetzt den "_gameOwn" Ordner eingeführt, In dem stecken alle Übersetzungen des Grundspiels für die Fruchtsorten, Paleten usw. sowie Fahrzeuge.
Im den Ordnern für die Modmaps dann nur doch deren spezifische Sachen. Man könnte das auch über die Benamsung der Dateien lösen wie map_irgendwas1.xml, map_irgendwas2.xml und dann erw_irgendwas3.xml. Ich denke die Masse an Dateien wird es ja nicht, oder?
Ich hab auch kein Problem damit, wenn ich noch nach Unterordnern suche und darin nach XML-Dateien. Nur lohnt das in meinen Augen erst, wenn man viele Dateien hätte. (So wie anfangs für jedes Kartenobjekt eine einzelne Datei anlegen wollte, was sich als ziemlich unpraktisch erwiesen hat)

**Comment by alex83we** [comment]
ich habe zum beispiel ein Projekt laufen was aktiv ist und ich will da per FTP auf den Ordner in der Kartenkonfiguration zugreifen ohne irgendwas an der karten Konfigutation zu ändern 

z.b.: 

> FTP zugang auf den Ordner /ergaenzungen/ und nur diesem ordner die rechte geben das sie von jedem der FTP zugang hat bearbeitet werden können ohne jedoch an die haupt Config zu müssen.

Weil sagen wir mal ein Mapper eine neue Produktion eingebaut hat oder jemand zum beispiel die Marsch hat und dort noch x neue Produktionen verbaut hat oder AdBlue Tankstellen oder was weiß ich auch immer.

also 

> config/nfmarsch/*.xml sind datein die der user nicht erreichen soll z.b.

und jetzt der ordner der von jedem erreicht werden kann der den ftp zugang hat:

> config/nfmarsch/zusatzordner/*.xml weil der hoster der die stats hostet zum Beispiel nicht möchte oder sich seine erweiterungen trennen will 

oder man einfach für die Übersetzung einen eigenen Ordner macht so wie jeder mag du

**Comment by J0hnHawk** [comment]
Würde dir/euch auch ein Ordner auf der 'config'-Ebene reichen? Das ließe sich sehr einfach realisieren.
Die Struktur würde dann so aussehen:
![grafik](https://user-images.githubusercontent.com/13779553/35388140-dd68a74a-01d2-11e8-8e8c-fc9471f08b23.png)

**Comment by alex83we** [comment]
wenn er dann die jeweilige config aus liest ist alles okay wo der ordner liegt ist egal

**Comment by J0hnHawk** [comment]
Okay, habe ich eingebaut. 
Es wird (bei XML Konfigurationen) nun zusätzlich nach der Ordner "ZZZ_additional" eingelesen, wenn er vorhanden ist.
