### ISSUE TITLE
Produktionen mit dem gleichem Endprodukt

### ISSUE THREAD

**Issue by alex83we** [J0hnHawk/FS17_WebStats#63]
Ist es möglich Produktionen mit gleichem Endprodukt zusammen zufassen zu einer Produktion habe das schon öfter das man von einer Produktion mehrere Zweigstellen hat und auf der HofBergmann ist das extrem da hat man 46 Äpfelbäume und jeder ist eine Produktion 

![screenshot_3](https://user-images.githubusercontent.com/10686163/35471945-f154a30a-0365-11e8-918d-5e1b2d339874.png)

**Comment by J0hnHawk** [comment]
Überlegt hatte ich das auch schon. Auf der NF Marsch gibt es ja den Baumarkt mit den 4 Paletten, die man dort kaufen kann. Die hätte ich auch gerne zusammen gefasst. Aber das funktioniert leider nicht so einfach. 
Da muss das komplette Datenmodell erweitert, bzw. angepasst werden. Und das zieht sich nahezu durch den gesamten Programmcode.
Keine Ahnung, was den Mapbauer geritten hat, bzw. warum er diese Lösung (46 Apfelbäume) gewählt hat, bzw. wählen musste. Aber gefühlt ist das nicht die beste Lösung. Das Spiel muss in dem Fall ja weit mehr Trigger/Produktionsstätten verwalten.
Lange Rede - ich behalte es im Hinterkopf.

**Comment by alex83we** [comment]
okay danke

**Comment by J0hnHawk** [comment]
Die Zusammenfassung von Betrieben mit dem gleichen Endprodukt werde ich nicht einbauen. Abgesehen davon, dass das aktuelle Datenmodell eine Zusammenfassung nicht erlaubg, wie soll man bei einer Zusammenfassung in Erfahrung bringen, an welchem Apfelbaum (Beispiel oben) Wasser oder Kompost fehlt, bzw. bei welchem Baum das Produktlager voll ist. Gleiches gilt für die kaufbaren Paletten beim Baumarkt auf der NF Marsch Karte.
