### ISSUE TITLE
Default settings + 2 tips

### ISSUE THREAD

**Issue by ghost** [J0hnHawk/FS17_WebStats#65]
Hello,
Would you be able to set default language and style settings?
Example:
czech and bootstrap style

For all visitors.

Thanks JanSe

**Comment by ghost** [comment]
One more tip:
template/husbandry.tpl
Line:11,94
Change:
```
OLD:	
<strong>{$animalPlant}</strong>
NEW:
<strong><a href="index.php?page=factories&object={$animalPlant}">{$animalPlant}</a></strong>
```

:)

**Comment by ghost** [comment]
Next tip: :)
templates/production.tpl
Line:65-71
```
**Original**
						</div>
						<div class="col-sm-3">
							<p class="pull-right">
								<a href="index.php?page=production&hide={$plantName|base64_encode}"><span class="glyphicon glyphicon-eye-close"></span> ##HIDE##</a><br>
								<a href="index.php?page=factories&object={$plantData.i3dName}"><span class="glyphicon glyphicon-eye-open"></span> ##MORE_DETAILS##</a>
							</p>
</div>

**Change to:**
							<p class="pull-left">
								<a href="index.php?page=production&hide={$plantName|base64_encode}"><span class="glyphicon glyphicon-eye-close"></span> ##HIDE## </a>
							</p>
							<p class="pull-right">
								<a href="index.php?page=factories&object={$plantData.i3dName}"><span class="glyphicon glyphicon-eye-open"></span> ##MORE_DETAILS##</a>
							</p>
						</div>
```

**Comment by ghost** [comment]
preview
![vystrizek](https://user-images.githubusercontent.com/35608485/35482173-a478e65a-0431-11e8-8709-0242d3bbb09f.PNG)

**Comment by alex83we** [comment]
das haben wir doch schon so und ich finde es so wie es jetzt ist besser

**Comment by ghost** [comment]
This is better for mobile control...

**Comment by alex83we** [comment]
ja dann kann man das bei mobilen ansichten ändern und das soll mit der 1.5 kommen

**Comment by alex83we** [comment]
#56

**Comment by J0hnHawk** [comment]
I'll add the link to factory on animal page with the next commit.

I could add an option to set the default language and style while installation in version 1.5 . Problem is, the default language must contain all translations in the map config and website. If not an error could occur.

Moving the links in production overview from right to bottom might be an option. On my phone both links are on the right side under the products. 

In the meantime, if someone don't like my default styles, just copy them to a new folder, change the name in style.cfg and modify the style like you want. ;-P

**Comment by alex83we** [comment]
Genau so sehe ich das auch ich glaube die styles sind vollkommen okay, und bei meinem Samsung s8 sind sie auch unter den Produkten.

Und wie gesagt man kann auch nicht alle Darstellungen in der mobilen Ansicht und auf jedem Gerät zu 100% optimieren.

Ich glaube da sollte sich jemand selber die Arbeit machen und es für sich anpassen denn man darf nicht vergessen das wir das in unserer Freizeit machen und nicht beruflich und völlig kostenlos.

Meine Kartenkonfigurationen sind teilweise nur in Deutsch denn ich denke das sich jemand seine Sprachen selber anpassen kann, wenn er unbedingt eine andere Sprache möchte.

**Comment by ghost** [comment]
I also help you in my spare time and completely free of charge.
It did not matter, it was just an idea.

I have my own modified style ...

I close ...

**Comment by alex83we** [comment]
Ja das ist ja auch okay nur wäre die idee hier #56 besser aufgehoben gewesen. 

war ja auch keine Kritik an dich agrofs17

**Comment by J0hnHawk** [comment]
I'll reopen this issue. 
I think setting the default language during installation is a useful option. If translations are missing, the program could use the ingame names for triggers or commodities and the names of the placeholders (##TEXT###) on the website. 
Setting the style during installation is completely uncritical. And if someone doesn't want the users to be able to change it, you simply delete the other styles.

Oh, and please don't get me wrong. 
I am happy about the tips and help with the website! 

I just wanted to say that if someone is totally unhappy with the things I've created or a program change takes too long: WebStats is hopefully modifiable enough to adapt it to your own wishes.

**Comment by ghost** [comment]
OK, i'm glad i can help with webstats. :) 👍
