### ISSUE TITLE
Verkaufsübersicht Max/Min händisch eintragen

### ISSUE THREAD

**Issue by alex83we** [J0hnHawk/FS17_WebStats#66]
Wäre es möglich bei der Verkaufsübersicht wo man die Preise der einzelnen waren sieht
Hinter den waren ein Feld zu erstellen wo man händisch was eintragen kann was jeder sieht?
Weil da könnte man dann eintragen was der höchste Preis bis dato für dieses Produkt war
Und man hätte ne Übersicht ob der VK Preis gut ist oder nicht

Intressant für Spieler die mit dem Season Mod spielen

**Comment by J0hnHawk** [comment]
Ja, das wäre möglich - ich hätte aber noch eine viel bessere Möglichkeit: Die Preise lassen sich vorausberechnen...
Kennst du die Mod Commoditiy Prices? Fed Action legt das seiner NF Marsch Karte bei. Ich hab mir überlegt, die Mod auf der Webseite nachzubauen. 
Blöd bei den Verkaufspreisen ist nur, dass man ggf. nicht alle Trigger erwischt. Die Verkaufsstellen der Züge werden nicht im Savegame gespeichert. Auf großen Karten fällt das nicht so ins Gewicht. Auf NF Marsch fehlt glaube ich nur der Bahnhof. Auf Sosnovka sind es dann schon 3 Verkaufsstellen (Transportfirma, Mühle und ... hab vergessen wie der Rüben- und Kartoffelverkauf heißt). 
Wie ist das auf den Karten für die du Konfigurationen erstellt hast? Gibt es da Züge, bzw. Züge die man wegschicken kann zum Verkaufen?

**Comment by alex83we** [comment]
genau das war der plan :-)

**Comment by alex83we** [comment]
das ist glaube aktuell nur auf der Moris land so der Fall und die Züge kannst du doch auslesen die sind als train declariert und soweit ich mich entsinne funktioniert das auch

**Comment by J0hnHawk** [comment]
Dann weißt du mehr als ich - wenn wir beide von den Verkaufspreisen an den Bahnhöfen sprechen ;-)

Hier einer der Züge auf Sosnovka:
`<onCreateLoadedObject saveId="Train_grainTrain1_grainTrainSpline1" isTrainStarted="false" currentTime="0.031823402157265" direction="1" lastSpeed="0">`
`<vehicle1 fillLevels="" fillTypes="" />`
`<vehicle2 fillLevels="0 0 0" fillTypes="wheat barley sunflower" />`
`<vehicle3 fillLevels="0 0 0" fillTypes="rape soybean maize" />`
`<wood fillLevel="0" />`
`</onCreateLoadedObject>`

Man sieht nur, dass an dem Bahnhof etwas verkauft werden kann und was. Aber leider nicht zu welchem Preis. 
Hm, könnte ich eigentlich auch mal einbauen. Also das "das" und "was" :-)

**Comment by alex83we** [comment]
Ah ja okay gut die kenne ich nicht und glaube auch das ist ganz tief im giants verankert das bekommen wir nicht ausgelesen  da ja die wichtigen infos fehlen :-(

**Comment by J0hnHawk** [comment]
Neue Preisübersicht eingebaut. Bahnhöfe bleiben unberücksichtig.
