### ISSUE TITLE
Symbole verschwinden

### ISSUE THREAD

**Issue by alex83we** [J0hnHawk/FS17_WebStats#67]
Kannst du mir sagen woran es liegt das die symbole in der Serverübersicht verschwinden beim drüberfahren

**Comment by J0hnHawk** [comment]
Mh, die overview.tpl eine abgespeckte Version des original Codes von Giants. Was der Hoover-Effekt mal bezwecken sollte, weiß ich nicht. Beim drüber fahren wird die eine Grafik durch eine andere ersetzt, die aber gleich aussieht. Das zurücktauschen beim Verlassen des Mauszeigers funktioniert offensichtlich nicht mehr richtig. Wahrscheinlich hat mir Eclipse beim Code formatieren wieder das die Style-Angaben kaputt formatiert. 
Ich schau mir das nachher mal an.

**Comment by alex83we** [comment]
ich dachte erst es liegt an meinem Server oder am php 7 aber nö ist mit php 5 das selbe einfach den hover rausnehmen fertig :-)

**Comment by J0hnHawk** [comment]
Geht wieder (b7f91fbf4260eda04791c80e9058a6495aa653c4). Bei der Umstellung auf die Styles hatte ich die Anpassung einer URL vergessen.

**Comment by alex83we** [comment]
jetzt bleiben die icons gross ist das so gewollt ???

**Comment by J0hnHawk** [comment]
Nein. Groß sollen die gar nicht werden. Werden sie bei mich auch nicht - weder im Firefox noch im Edge. Chrome und Mobil hab ich noch nicht ausprobiert.

**Comment by alex83we** [comment]
chrome und edge bleiben sie gross

**Comment by alex83we** [comment]
firefox auch 

Opera auch

http://prntscr.com/i78wvd

**Comment by J0hnHawk** [comment]
Das macht irgendwie überhaupt keinen Sinn... wenn du dir mal die Zeilen 34ff in der overview.tpl anschaust, dann ist da gar keine Angaben über die Bildgröße bei den Hoover-Effecten. Und die Bilder sind alle 26 Pixel "groß".

**Comment by alex83we** [comment]
css ?

**Comment by alex83we** [comment]
Javascript regelt hier glaube einiges 

![screenshot_1](https://user-images.githubusercontent.com/10686163/35523272-bff8d2f8-051e-11e8-89c7-2477f62a0e4d.png)
![screenshot_2](https://user-images.githubusercontent.com/10686163/35523273-c01738ba-051e-11e8-844e-9d9d2bde23c9.png)

**Comment by J0hnHawk** [comment]
Bei dir fehlen die Größenangaben.
<img id="vehicle11Image" src="./styles/fs17/images/trailer.png" **width="10" height="10"**>
Die stehen bei mir im F12-Menü bei allen Grafiken, sowohl "selected" oder nicht, dabei.

Dies ist die entsprechende Zeile in der overview.tpl:
`<img id="vehicle{$key}Image" src="./styles/{$style}/images/{$mapEntry.icon}" width="{$machineIconSize}" height="{$machineIconSize}">`

Ich habe das jetzt noch am Rechner meiner Frau und Sohnes ausprobiert - da sieht auch alles schön aus.

**Comment by alex83we** [comment]
ich habe alles gelöscht und so ich weiss nicht warum er das hovert :-(

**Comment by J0hnHawk** [comment]
Mysteriös. Aber die Seite muss beim Mobile-Update auch von Grund auf erneuert werden. Die Grafik ist ja viel zu groß für das Smartphone.

**Comment by alex83we** [comment]
ich habe das auf allen rechnern so :-( ja das stimmt oder die karte responsiv laden mit ner max größe

**Comment by J0hnHawk** [comment]
Die Berechnung der Positionen muss dazu in das Template verlagert werden. Im Moment werden die ja noch auf Seiten des PHP Codes berechnet.

**Comment by alex83we** [comment]
kannst du die karte nicht auf eine maximale größe begrenzen zb.: 320 px das ist die minimale größe die ich optimieren würde und da kann man ja sicher auch weiter hin in php bereechnen denn jetzt ist die karte ja auch 512 x 512 die wichtigste karte ist ja die warenübersicht und die server karte bissel kleiner rendern
