### ISSUE TITLE
Weitere Tiere 

### ISSUE THREAD

**Issue by alex83we** [J0hnHawk/FS17_WebStats#68]
ich bin aktuell an der Hof Bergmann da gibt es ja das ein oder andere was nicht so normal ist unter anderem Gänse und Pfohlen diese werden als Paletten ausgelesen aber irgendwie finde ich keinen Paletten Trigger und die Tiere werden nicht angezeigt das läuft über [mCompanyFactory](http://mcompany-info.de/)  vielleicht gibt es da ja doch irgendwas, was anders ist.

[pfohlen.txt](https://github.com/J0hnHawk/FS17_WebStats/files/1673937/pfohlen.txt)

**Comment by alex83we** [comment]
Weitere mCompanyFactory Sachen 



```
  <item name="mCompanyFactory_cabbageField01" locationType="FabrikScript" ProdPerHour="100" position="-636.156 134.853 -828.991" showInProduction="true">
    <input name="cabbageField_saplings" capacity="98" factor="0.12" fillTypes="redCabbageSaplings" showInStorage="false"/>
    <input name="cabbageField_water" capacity="10000" factor="0.88" fillTypes="water" showInStorage="false"/>
    <output name="cabbageField_redCabbage" capacity="1" factor="1" fillType="redCabbage" palettArea="-621.08 -821.60 -650.93 -836.25" palettPlaces="98" showInStorage="false"/>
  </item>
  <item name="mCompanyFactory_cabbageField02" locationType="FabrikScript" ProdPerHour="100" position="-636.156 135 -850.98" showInProduction="true">
    <input name="cabbageField_saplings" capacity="98" factor="0.12" fillTypes="redCabbageSaplings" showInStorage="false"/>
    <input name="cabbageField_water" capacity="10000" factor="0.88" fillTypes="water" showInStorage="false"/>
    <output name="cabbageField_redCabbage" capacity="1" factor="1" fillType="redCabbage" palettArea="0 0 1 1" palettPlaces="98" showInStorage="false"/>
  </item>
  <item name="mCompanyFactory_cabbageField03" locationType="FabrikScript" ProdPerHour="100" position="-636.156 135.008 -873.676" showInProduction="true">
    <input name="cabbageField_saplings" capacity="98" factor="0.12" fillTypes="redCabbageSaplings" showInStorage="false"/>
    <input name="cabbageField_water" capacity="10000" factor="0.88" fillTypes="water" showInStorage="false"/>
    <output name="cabbageField_redCabbage" capacity="1" factor="1" fillType="redCabbage" palettArea="0 0 1 1" palettPlaces="98" showInStorage="false"/>
  </item>
```

vehicles.xml

```
    <onCreateLoadedObject saveId="mCompanyFactory_cabbageField02">
        <Rohstoff Name="cabbageField_water" Lvl="15875"/>
        <Rohstoff Name="cabbageField_saplings" Lvl="0"/>
        <Produkt Name="cabbageField_redCabbage" Lvl="0"/>
    </onCreateLoadedObject>
```

**Comment by J0hnHawk** [comment]
Wenn du die Grundkonfiguration mit meinem readMaoConfig Script ausgelesen/erstellt hast - mein Script geht bei Kapazitäten von unter 10.000 Litern davon aus, dass bei der Produktionsstätte Paletten hergestellt werden.
Hast du im Spiel mal geschaut, was dort hergestellt wird?
Weißt du, was das "drop" Attribut aussagt?

**Comment by J0hnHawk** [comment]
Bei den Rotkohlfeldern genau das gleiche - Kapazität unter 10.000. Darum nimmt mein Script die Palettenherstellung an.

**Comment by alex83we** [comment]
das sind tatsächlich paletten

**Comment by alex83we** [comment]
98 stück an der zahl

**Comment by J0hnHawk** [comment]
Ach du ... 98 einzelne Felder??? O.o 
Ist das die gleiche Karte, auf der auch 46 Apfelbäume verbaut sind?
Aber wenn es tatsächlich Paletten sind, passt die Angabe in der Konfiguration ja grundsätzlich. Spawnt da an jedem Baum/Feld eine eigene Palette?

**Comment by alex83we** [comment]
nein das ist ein feld mit 98 pflanzen diese aber als paletten  gesehen werden und ja es ist die map 

![screenshot_10](https://user-images.githubusercontent.com/10686163/35519462-9b564d68-0514-11e8-99d3-0f32e759be6c.png)

**Comment by alex83we** [comment]
ich weiss nicht was der drop für ein wert ist und so richtig gibt es auch keine angabe

**Comment by alex83we** [comment]
ist wohl ein unsichtbarer Haufen für die heap trigger siehe lua  

[mCompanyFactory.zip](https://github.com/J0hnHawk/FS17_WebStats/files/1674213/mCompanyFactory.zip)

**Comment by alex83we** [comment]
Kann es sein das die Paletten Stellplätze nach einem bestimmten Schema abläuft denn ich habe heute bissel probiert und x1 z1 + x2 z2 nach bestimmten Schemen abläuft. siehe Code

```
  <item name="mCompanyFactory_cabbageField01" locationType="FabrikScript" ProdPerHour="100" position="-636.156 134.853 -828.991" showInProduction="true">
    <input name="cabbageField_saplings" capacity="98" factor="0.12" fillTypes="redCabbageSaplings" showInStorage="false"/>
    <input name="cabbageField_water" capacity="10000" factor="0.88" fillTypes="water" showInStorage="false"/>
    <output name="cabbageField_redCabbage" capacity="1" factor="1" fillType="redCabbage" palettArea="-652.313 -837.629 -618.185 -820.437" palettPlaces="98" showInStorage="false"/>
  </item>
  <item name="mCompanyFactory_cabbageField02" locationType="FabrikScript" ProdPerHour="100" position="-636.156 135 -850.98" showInProduction="true">
    <input name="cabbageField_saplings" capacity="98" factor="0.12" fillTypes="redCabbageSaplings" showInStorage="false"/>
    <input name="cabbageField_water" capacity="10000" factor="0.88" fillTypes="water" showInStorage="false"/>
    <output name="cabbageField_redCabbage" capacity="1" factor="1" fillType="redCabbage" palettArea="-652.313 -860.097 -618.185 -842.338" palettPlaces="98" showInStorage="false"/>
  </item>
  <item name="mCompanyFactory_cabbageField03" locationType="FabrikScript" ProdPerHour="100" position="-636.156 135.008 -873.676" showInProduction="true">
    <input name="cabbageField_saplings" capacity="98" factor="0.12" fillTypes="redCabbageSaplings" showInStorage="false"/>
    <input name="cabbageField_water" capacity="10000" factor="0.88" fillTypes="water" showInStorage="false"/>
    <output name="cabbageField_redCabbage" capacity="1" factor="1" fillType="redCabbage" palettArea="-652.313 -882.578 -618.185 -864.829" palettPlaces="98" showInStorage="false"/>
  </item>
```
 
so das es wie jetzt aussieht und in der Übersicht der link ausgegeben wir und nicht Landschaft 98 (Paletten)

![screenshot_3](https://user-images.githubusercontent.com/10686163/35531876-9bf503b2-0538-11e8-9641-c8cb23f44398.png)

**Comment by J0hnHawk** [comment]
Die Funktion "getLocation" durchsucht alle Fabriken und innerhalb der Fabriken die Produkte und sucht nach den palettAreas. Die erste passende, die die Funktion findet, gewinnt. Das ist das ganze Schema ;-)

Ich hab für die NF Marsch sämtliche palettAreas noch mal neu ausgemessen indem ich alle Rohstoffe bei den Fabriken voll gecheatet habe, dann den Zeitraffer auf 120 gestellt habe und gewartet habe, bis alle Fabriken voll waren.
Die Positionen der Paletten habe ich dann in eine OpenOffice Tabelle exportiert, gerundet, ein bisschen Spielraum hinzugefügt und die ermittelten palettAreas in die XML eingefügt.

**Comment by alex83we** [comment]
genau so mache ich das auch anders würde ja ewig dauern :-)

**Comment by alex83we** [comment]
Hm ich glaub ich habe da eine false zuviel gesetzt bei den Tierchen :-)

**Comment by J0hnHawk** [comment]
:-D
Okay, das eigentliche Problem mit den Tieren ist damit erledigt?
Die Geschichte mit den Rotkohlfeldern ist ja letztlich die gleiche Problematik wie bei #63. Das behandeln wir dort.

**Comment by alex83we** [comment]
Nein das geht alles soweit
