### ISSUE TITLE
Anzeige Kaufbarer Objekte

### ISSUE THREAD

**Issue by alex83we** [J0hnHawk/FS17_WebStats#69]
wäre es möglich im Header einen weiteres Menü hinzuzufügen für Kaufbare Objekte  der nur erscheint wenn auf der Map kaufbare Objekte vorhanden sind das läuft über mCompanyFactory und ist aufgebaut wie eine Fabrik 

Wollte sowas ungerne in eine Produktionsübersicht machen. 
Also der type ist immer `mCompanyFactory_Buyable(durchnummeriert)` also könnte man das ja so lösen das wenn `mCompanyFactory_Buyable`  vorhanden ist der Button da wenn nicht verschwindet er (also eine true / false Abfrage) muss auch nicht im Header sein kann auch in der Produktions Übersicht sein in dem Header hinter ( Produktionsübersicht (Speicherstand: Tag 18, 22:16) ).
```
    <onCreateLoadedObject saveId="mCompanyFactory_Buyable02">
        <Rohstoff Name="buyable_moneyInput" Lvl="250000"/>
        <Produkt Name="empty" Lvl="0"/>
    </onCreateLoadedObject>
```

**Comment by J0hnHawk** [comment]
Das wäre bestimmt möglich. Aber ich werde diese ganzen Sonderlocken von mCompany erst mal nicht einbauen. Mir fehlt schlicht die Zeit, mich intensiv damit zu beschäftigen.

Wenn du die savegame.php unangetastet lassen möchtest, würde ich diese Buyable-Sachen erstmal über den locationType="extraFilePHP" abhandeln. Da kannst du mit einem extra Script die Dinger auslesen und am besten in einem neuen Array speichern. Für die Anzeige kannst du dann ja ein Style kopieren, das für die Karte anpasst, um das Buyable-Array anzuzeigen.

**Comment by alex83we** [comment]
schade ich wollte doch nicht in den php code eingreiffen :-(

**Comment by alex83we** [comment]
am ende war es nur eine idee mehr nicht war jetzt nicht so das man das braucht alles gut
