### ISSUE TITLE
pallet area

### ISSUE THREAD

**Issue by Dannydaboy** [J0hnHawk/FS17_WebStats#73]
Hello,

i will adding some pallet areas in my fabrik.xml but how can i find my x1 z1 x2 z2 coordinates?

the 4 points in my game are 182 757 - 182 774 - 178 265 and 178 774 the coordinates can i read in the game on the mini map. I calculate this to the Cartesian coordinate system (in game coordinate - 1024 (normal size map) thats al fine but how can i get the X1 Z1 X2 Z2 from the Cartesian coordinate system

**Comment by J0hnHawk** [comment]
Hi,
the lowest x-coordinate is X1 the highest one is X2. Same to z-coordinates. In your case X1 = 178, Z1 = 265, X2 = 182 and Z2 = 774. But I assume, you have an error in Z1. The area should be a rectangle. So I think your Z1 is 757?

For the XML, 1024 substracted, X1 = -846, Z1 = -267, X2 = -842 and Z2 = -250 (red dots)
![coordinates](https://user-images.githubusercontent.com/13779553/42146641-51881652-7dc9-11e8-9d64-b5e50887b47b.png)

**Comment by Dannydaboy** [comment]
My pallet is not a rectangle it missen one corner, i test it tonight and give a reply with the result. Thank tou for the fast answer!

**Comment by Dannydaboy** [comment]
hi the solution works for, is there a simple way to get the game coordinates from fs17 or only possible in game (in the mini map)? maybe in the giant editor, mod or some xml files?
thany you for the fast and worked solution

**Comment by J0hnHawk** [comment]
I used the Giants Editor a long time. I put a fencing post at the edges of the pallet area and noted the coordinates.

For the last map configs I used an OpenOffice Sheet. But there are some more things you have to do.

1. Start a new game on the modmap and save the game. It's a little bit easier if you sell all vehicles before.
2. Open the vehicles.xml with a texteditor. Edit all input storages of a factory to maximum (e.g. 10 million - the game reduces automaticliy if there is not enoug space) and save the file.
3. Load the savegame and wait until all pallet spawner are full.
4. Save the game and open the vehicles.xml with your texteditor again. Now copy all pallet entires and paste them to the OpenOffice Sheet I commited today (03e8cec72bf43bb2521fe5efbec7c65a17662086). You need to sort the pallets.
5. The sheet generates an export string wich you can copy and paste to your map config.

The sheet is quick and dirty... you need some expirience in sheets to handle it. But for me it was faster than determining the coordinates with the giants editor.

**Comment by Dannydaboy** [comment]
thats a nice sheet but i try to define another pallet area and its not work something wrong

ingame coordinates 82 792 \82 795 \97 795 \97 792 are the ingame coordinates, the lowest x-coordinate is X1 thats 81 in my opinion X2=97 Z1=792 and Z2=795 

i notice in my xml -943 -232 -927 -229 but thats wrong when i have the coordinates 82 792 \82 795 \97 795 \97 792 where must i start for define my X and Z coordinates i have 8 cordinates how can i set this to 4 coordinates (x1,x2,z1,z2)

**Comment by J0hnHawk** [comment]
The ingame coordinates shown at the minimap are not 100% accurate. Using the coordinates out of your vehicles.xml or from giants editor is better.

If you use the coordinates in the vehicles.xml, use the min-x-coordinate of your 8 pallets as X1 and the max-x-coordinate as X2. Same to z-coordinates.

eg:
![pallets](https://user-images.githubusercontent.com/13779553/42216286-9c65e19c-7ec1-11e8-9d6a-4b6f324f78b0.png)

X1 for these 8 pallets is 81, Z1 is 232, X2 is 84 and Z2 is 233

**Comment by Dannydaboy** [comment]
I have use the giant editor and see there 3 cordinates X,Y and Z i recover the folowing coordinates
X:-926  - 926  -942  -942
Y:86  86  86  86 
Z:-228  -230 -230 -228

I have recover X1-926 Z1-228 X2-942 Z2 -230 I subastracted the 1024 result X1=-1950, z1=1252, X2=-1966 and Z2=-1254 and notice that in my xml but no pallets showing up what do i wrong?

Sorry for the questions but i am not so strong in numbers.

**Comment by J0hnHawk** [comment]
No problem :-)
If you use the coordinates shown in Giants Editor, you don't have to substract 1024. 
Also if you use the coordinates in the vehicles.xml you don't need to to substract 1024.

Only if you use the ingame coordinates you need to substract 1024.

**Comment by Dannydaboy** [comment]
i have give it a try but no succeed i think there something wrong 
my xml data
-boardPallet.i3d" position="-927.08807373047 86.113777160645 -229.67698669434"
-boardPallet.i3d" position="-937.125 86.11376953125 -229.67700195313"
-boardPallet.i3d" position="-931.10656738281 86.113777160645 -229.67698669434"
-boardPallet.i3d" position="-941.11309814453 86.113777160645 -229.67098999023"
-boardPallet.i3d" position="-939.12506103516 86.11376953125 -229.67700195313"
-boardPallet.i3d" position="-933.11022949219 86.113777160645 -229.67700195313"
-boardPallet.i3d" position="-929.09893798828 86.113777160645 -229.67698669434"
-boardPallet.i3d" position="-935.11846923828 86.11376953125 -229.67700195313"

total 8 pallets (10.000 each) i locate the following Z1=-927 X1=-229 X2=-941  Z2=-229
When i note this to my xml in webstats ther only show 1 pallet to the fabrik what do i wrong or is there something wrong with the map

**Comment by J0hnHawk** [comment]
There is a little mistake... -941 is smaller than -927 ;-)
I would suggest: X1 = -941.8 Z1 = -230.4 X2 = -926.4 Z2 = -229.0

It is a good idea to round down and up the coordinates. If you move the pallets ingame accidently there is a chance that they are still in the area.

- The lowest x coordinate of your pallets above is -941.11309814453. 
Rounded to -941.1 and 0.7 substracted x1 = -941.8.
- The lowest z coordinate of your pallets above is -229,67700195313. 
Rounded to -229.7 and 0.7 substracted z1 = -230.4.
- The highest x coordinate of your pallets above is -927.0880737. 
Rounded to -927.1 and 0.7 added x2 = -926.4.
- The highest z coordinate of your pallets above is -229.67099. 
Rounded to -229.7 and 0.7 added z2 = -229.0.

**Comment by Dannydaboy** [comment]
its work! i will thank you so much and go further on my other pallet places you have help me out!

**Comment by Dannydaboy** [comment]
i have try another pallet and the site  shows 5 pallets in factory and 1 pallets on the map

i find the following x and y coordinates in my xml (6 pallets)
-958.159   -274.685
-962.153   -274.680
-956.162   -274.684
-960.159   -274.685
-960.834   -263.843
-954.167   -274.684

X1=-962.153 Z1=-274.685 X2=-954.167 Z2=-263.843 

i rounded to 962.2  274.7  954.2 and 263.8 and substracted  0.7

Result
X1=-962.9  Z1=-275.4 X2=-954.9 Z2=-263.2

i notice the folowing in my xml
palettArea=-962.9 -275.4 -954.9 -263.2"


what going wrong

**Comment by J0hnHawk** [comment]
Hi,
sorry for the late answer.
You substracted 0.7 at X2 - you have to add 0.7 ^^ 
X2 = 953.5

**Comment by Dannydaboy** [comment]
no problem for the late answer, i see now the pallets on the site thats work but i think i have another problem. on my start site where i can see al my products (index.php) i see 4.142 / 5.000 only 1 pallet on that site it must be 29.142 / 30.000 can i configurate that somewere?

i notice in my php 
< output name="palette" capacity="5000" factor="1" fillType="palette" palettArea="-858.9 -231.5 -833.4 -197.4" palettPlaces="5" showInStorage="true" />

**Comment by J0hnHawk** [comment]
Mh, this is a translation problem if I remeber right.

E.g. planks can have 3 different game internal name. All must be translated in the xml-files.
`<text name="boardPallet"><en>Planks</en><de>Bretter</de><fr>Palette de planche</fr></text>`
`<text name="boardwood"><en>Planks</en><de>Bretter</de><fr>Palette de planche</fr></text>`
`<text name="Bretterpaletten"><en>Planks</en><de>Bretter</de><fr>Palette de planche</fr></text>`

`<text name="game internal name ">`
`<en>english translation</en>` 
`<de>german translation</de>`
`<fr>french translation</fr>`
`</text>`
You don't need all languages.
