### ISSUE TITLE
Map Config

### ISSUE THREAD

**Issue by chr1974** [J0hnHawk/FS17_WebStats#76]
Hi, nice script, how do you make map configs? where to find the correct values? I would like to add shamrock valley by oxygendavid to it. is it possible?

**Comment by J0hnHawk** [comment]
Yes, it should be possible. I made a little script "readMapConfig.php" in tools folder. 
Copy mapXX.i3d to the same folder an edit the filename in the script. It should generate most of the factoryscript parts.
I got the pallet area and other coordinates with the giants enditor. Second way is to get the coordinates ingame. Just take a look into the wiki here. In the wiki i described the former php configuartion files. if you compare these with the actual xml files you should be able to create an own map config.

**Comment by chr1974** [comment]
Cool, Thank you, will try to make it

**Comment by chr1974** [comment]
have tried it, only returned an empty array. it is only the map01.i3d file I copy into the dir where readMapConfig.php resides?

**Comment by J0hnHawk** [comment]
Did you edit Line 22?
$xmlStr = file_get_contents ( './map01_nfm4f13.i3d' );

Last time I used the script i renamed the i3d-file ;-)

**Comment by J0hnHawk** [comment]
Closed due no more answer.
