### ISSUE TITLE
You don't have permission to access / on this server.

### ISSUE THREAD

**Issue by Faithnall** [J0hnHawk/FS17_WebStats#77]
after trying to start a fresh Install on my Webspace

**Comment by J0hnHawk** [comment]
This is not an error message of my script. But... [magic glass ball on] I assume the webserver has no rights to create the cache files [magic glass ball off] :-P

Set the permissions to "644" for the webstats directory and all contained files and (sub)folders.

**Comment by Faithnall** [comment]
Found the error, provider error on the topfolder.
Same install on subfolder of other domain works fine :)
