### ISSUE TITLE
division by zero

### ISSUE THREAD

**Issue by bl4ckdog** [J0hnHawk/FS17_WebStats#9]
Nach update und neuinstallation von Commit a8a3ec2 
Division by zero in functions.php, line 44

![Screenshot](http://7g973vws.tk/uploads/2017/09/i234bmi214.png)

**Comment by bl4ckdog** [comment]
Doch kein Fehler.
Mein Speicherstand war korrupt, daher wurde nicht korrekt ausgelesen. Mit einem neuen, sauberen Speicherstand läuft alles einwandfrei.

**Comment by J0hnHawk** [comment]
Doch, war ein Fehler ;-) 
Der trat auf, wenn man noch keine Tiere gekauft hat aber die Futtertröge schon gefüllt wurden. 
Ich hab' das jetzt doppelt gefixt. Eine Division durch 0 wird an der Stelle abgefangen (#10) und die Futtertroggröße wird auf die des Inhalts gesetzt, wenn die errechnete Größe (abhängig von der Anzahl der Tiere) kleiner ist als der Inhalt (#11).

**Comment by bl4ckdog** [comment]
Oh... okay. hurra - ich habe nach langer Zeit mal wieder was gefunden. :)
